### ISSUE TITLE
Project Planning - knitting patterns, backend, frontend, knitting pattern editor

### ISSUE THREAD

**Issue by mariobehling** [fashiontec/knitapps#12]
Project 1 (Sebastian): Develop Open Knitting pattern format, support plugin architecture of backend. Develop the architecture in a way to enable support of different front ends, e.g. web. Separate the functions to control and set the properties for each machine to be independent of qt.

Project 2 (Sameera): Plan and develop the web front end and pattern editor. Start with creating compelling and convincing mockups in awesome design. Develop it with Python and possibly use Flask as a framework or suggest another solution.

Project 3 (Shiluka): In an independent library implement support for additional machines and develop web backend. Add more plugins.

I see the following repositories, that we need to work on this:
a) knitpat (pattern format)
b) knitback (backend based on AYAB)
c) webknit (web app frontend and backend)
d) knitedit (pattern editor for the web app)

According to this outline, I am setting up different labels. Please create a list of features for each project.

Developments take place on github to enable us to follow each others activities easily. Additionally please merge relevant code with AYAB on bitbucket.

Does this all make sense to everyone?

**Comment by tian2992** [comment]
Roger, I will create a graphic with more implementation details and add it to this issue.

**Comment by sameeragunarathne** [comment]
Yes. clear on this. I will update the issue the design for the front end
and pattern editor. I am going to use flask for creating web api.

On Wed, May 20, 2015 at 10:37 PM, Sebastian Oliva <notifications@github.com>
wrote:

> Roger, I will create a graphic with more implementation details and add it
> to this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fashiontec/knitapps/issues/12#issuecomment-103963093>.
>



-- 
*Sameera Gunarathne*
Undergraduate of Department of Computer Science & Engineering of University
of Moratuwa

*+94714155561
<http://s.wisestamp.com/links?url=tel%3A%252B94716320074&sn=dmlwdWxhc2QyMDA3NEBnbWFpbC5jb20%3D>*

**Comment by shiluka** [comment]
Got it. I will update the issue with list of features for the web backend and the library.

**Comment by sameeragunarathne** [comment]
Project 2: Plan and develop the web front end and pattern editor

Design for Home Page
![screenshot from 2015-05-22 17 49 59](https://cloud.githubusercontent.com/assets/5234677/7770390/961d6522-00ab-11e5-8fef-172233701156.png)
This is the page where user gets soon after log in to the application. In this design user can keep track of the knitting work by managing them as seperate projects. User can choose a previously worked knitting project or a new one from here. 

Design for Pattern Editor
![screenshot from 2015-05-22 17 08 48](https://cloud.githubusercontent.com/assets/5234677/7770454/243af770-00ac-11e5-9003-f0e6893fff11.png)
After entering to a project user will be redirected to the workspace of the project. workspace consists of two major components. They are pattern editor and knitting simulator. In pattern editor user can load the pattern file as a image format and editor will pixelate the image according to user defined pixel dimensions. So that pattern will be easily editable according to the rows and stitches allowed for knitting. Editor provides tools for edit each cell on the grid formulated. User will be able to edit using  allowed RGB value ranges for each cell. Further more the functionalities like turn, flip, replicating(repeating) are intended to add to the pattern editor.

Design for Knitting Simulator
![screenshot from 2015-05-22 17 39 30](https://cloud.githubusercontent.com/assets/5234677/7770564/8c901458-00ad-11e5-9393-a0a4112cfc04.png)
This component of the workspace allows user to configure knitting details like needle position, color details etc and then start the knitting process .  Knitting simulator is there to give simulation of the knitting process to the user. In this knitting progress details are shown to the user both graphically and as a log.

**Comment by mariobehling** [comment]
@sameeragunarathne Please repost your above ideas and add a feature list and possible milestones to the dedicated issue here https://github.com/fashiontec/knitapps/issues/14

**Comment by mariobehling** [comment]
@shiluka Please add info about your project here https://github.com/fashiontec/knitapps/issues/15

**Comment by mariobehling** [comment]
@tian2992 Please find a dedicated issue for the project planning here https://github.com/fashiontec/knitapps/issues/13
