### ISSUE TITLE
Web app for knitting

### ISSUE THREAD

**Issue by mariobehling** [fashiontec/knitapps#4]
We would like to see an improved interface for our knitting application that can be used through a browser. This will give us the option of running a machine as a web app on any device. For now the goal is to install all the software on one PC. Future steps could be to run a small server on a Rapspi and access it through a mobile phone.

For now, please outline your ideas about the interface and the possible implementation of the knitting application. What abstraction layers and what components are required?

**Comment by sameeragunarathne** [comment]
Hi for the web interface If is it okay to use arduino ethernet shield to communicate with the web interface. I can give a design on both ethernet and wifi shields. And I have intended to do implementation on node js.

**Comment by mariobehling** [comment]
Please explain why you want to use Node.js rather than other solutions. What other options do we have?

**Comment by chris007de** [comment]
Another Hint from my side: Please check https://codebender.cc/.
They manage to interface with the Arduino directly from the Browser over the USB-Serial connection, no need for another (costworthy) Ethernet/Wifi Shield (which would increase the already bulky packaging of the hardware)

**Comment by sameeragunarathne** [comment]
@mariobehling That suggestion was done because of a previous implementation of a IoTHub for a Raspeberry pi using node js. It can be used implement lightweight application and good for I/O related implementations. Other than that Python/Java implementation would be good. 
@chris Affirmative that was there when using shields. It is a good suggestion and I will look into that

**Comment by mariobehling** [comment]
@sameeragunarathne Please give us some links for the examples you are referring to and tell us about the relevance to knitting machines.

**Comment by sameeragunarathne** [comment]
@mariobehling I have reffered to one of my projects done at the university and I have added it to the github. Here's the link: https://github.com/sameeragunarathne/nodeserver. For AYAB also uses the communication between the computer or any smart device with arduino with the AYAB shield plugged into it, and by using node js I thought it would be efficient for the serial communication.

**Comment by tian2992** [comment]
I think we can re-use our existing codebase by providing Web endpoints using Python (either REST or WebSockets). Other projects already use Python, such as the https://github.com/adafruit/knitting_machine 
Knittic seems to use Processing, which is based on Java, but quite simplified, so I would expect porting code based on their implementation could be done closer to a procedural implementation, rather than a callbacks based approach, as most JavaScript-serial interfaces are commonly implemented. 

I think we should build a Web API that can abstract over hardware connections (no direct serial access, etc), allowing for both the basic knitting operations and more advanced control depending on the machine.

**Comment by mariobehling** [comment]
@tian2992 Yes, we get here to the question of the implementation of the library. Could you give some more input on this point, please? https://github.com/fashiontec/knitapps/issues/3
