### ISSUE TITLE
What features do we want in a knitting app? Please help to make a feature list.

### ISSUE THREAD

**Issue by mariobehling** [fashiontec/knitapps#8]

**Comment by sameeragunarathne** [comment]
@mariobehling 

Feature list for knitting app

1. The knitting process should be started as a project which the user can save and manage the workings(i.e knitting configuration,material details) on the knitting inside the application.
2. Multiple formats of pattern input able to be added to the app (jpeg,gif,png,pdf,dat,html etc).
3. After loading the pattern user will able to edit the pattern inside the workspace as he/she preferred.
4. Patterns can be viewed as pixelated to the user as it is easily viewable and editable inside the workspace.
5. Simulation of the knitting process should be shown including graphical simulation of the pattern, list of events at a row, knitting direction etc.
6. GUI should be in several windows with a Home page with a options to select. User will be able to load a new project or a existing one and proceed to next windows following the relevant UI flow. 
8. User able to emulate the process by looking at the event flow of the knitting process before actual knitting starts.
7. User able to adjust the knitting configurations by pausing the knitting process.

In Addition since we are using a web API for the project we can give access to some sort of website to download sample patterns and try out the knitting configurations.

I am expecting Suggestions and Improvements on this before the full proposal on these features. 

Thank You.

**Comment by chris007de** [comment]
@sameeragunarathne 
Thank you, here are my comments on the following points:
2. Have you thought about the impairments of using compressed formats like jpeg?
Also, it is not always reasonable to allow a huge range of input formats, it just increases the effort for testing.
3. Pattern editing may be really sophisticated. Re-think if it might be an option to put this part in a dedicated part/mode of software.
5. I really like this idea
6. Also a nice idea, but keep in mind to keep it simple and lightweight
7. Please explain "event flow" more detailed

**Comment by sameeragunarathne** [comment]
@chris007de Hi Thanks for your points. 
2. I will try to implement the solution for as much as possible formats. In jpeg scenario can't we use a decorders in python to get worked on jpegs. 
3. In this case I am planning to add some image processing to pixelate a given image and enable editing on those pixels seperately.
7. Event flow is a collection of details of pattern meta data including carriage details, stitch details at each row which human can understand.
